/**
 * types/keyword.ts — Shared TypeScript Types
 * ============================================
 * Single source of truth for the KeywordResult shape.
 * Used by geminiService, processKeywordsForClient, and API routes.
 * All fields are plain JSON-serializable primitives — safe for HTTP responses.
 */

// ─── Core Response Interface ──────────────────────────────────────────────────
/**
 * Represents the Event Description generated by the AI.
 */
export interface EventResult {
  /** The generated event description. */
  description: string;
  /** Tokens used to generate this description */
  usage?: number;
}

// ─── API Response Wrapper ─────────────────────────────────────────────────────
/**
 * The clean HTTP response envelope sent back to the frontend.
 */
export interface KeywordsApiResponse {
  success: true;
  data: EventResult;
}

/**
 * Standard error response envelope for the API.
 */
export interface KeywordsApiErrorResponse {
  success: false;
  error: string;
}
